---
version: "3"

services:
    redis-db:
        image: redis:7
        ports:
            - 6379:6379
        volumes:
            - ./data:/data
        user: "1000:1000"
        command: ["--save", "1", "1"]

    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
            - redis-db
        environment:
            - REDIS_HOST=redis-db
            - LOG_LEVEL=WARNING
        image: jyl2027/neo_api:1.0
        ports:
            - 5000:5000
        command: ["python", "NEO_api.py"]

    worker:
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
            - redis-db
        environment:
            - REDIS_HOST=redis-db
            - LOG_LEVEL=WARNING
        command: ["python", "worker.py"]

